### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by nechar** [negativo/JWT-Auth-NodeJS-Starter-Kit#4]
**Description below:**
(You may want to double click the image for a better view)

![image](https://user-images.githubusercontent.com/10302035/72188701-135acd00-344f-11ea-913e-83d731aa9009.png)

**OS:** Windows 10

**Comment by negativo** [comment]
Thank you, will look into it

**Comment by nechar** [comment]
Thanks @negativo, looking forward to getting it fixed.

**Comment by negativo** [comment]
@nechar fixed on master, later I will update the README to make sure people don't use this project for production. Is an old project that is not supported right now.
